version: "3"
services:
  api:
    build:
      context: ./toolbox-api
    ports:
      - "3001:3001"
  react-app:
    build:
      context: ./toolbox-react/toolbox-app
    ports:
      - "3000:3000"
    depends_on:
      - api
